on: 
  workflow_dispatch:

jobs:
  chmodjob:
    runs-on: ubuntu-latest
    name: change mode
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: initialize
        run: |
          git add entrypoint.sh
          git update-index --chmod=+x entrypoint.sh
          git ls-files --stage entrypoint.sh
